--- 
- name: use register 
  hosts: 
    - web
    - servers
  tasks:
    - name: get datetime
      command: date +%s
      register: datetime

    - name: print datetime
      debug:
        var: datetime.stdout


