---
- name: changed when
  hosts: web
  vars:
    change: true
  tasks:
    - name: xxxxx 
      block:
      - name: task1
        debug:
          msg: "tell you  a message"
        notify: x2
        changed_when: change 

      - name: task2
        shell:  echo "hello"
      when: change

  handlers:
    - name: x2
      debug:
        msg: "handlers x2  running"

