---
- name: fail when
  hosts: web
  tasks:
    - name: get url 
      uri:
        url: "http://192.168.1.1/"
        method: GET
      register: uri_data
      failed_when: 200  in uri_data.status

    - name: debug uri info 
      debug:
        var: uri_data
