---
- name: no loop playbook
  hosts: web
  tasks:
    - name: start firewalld service
      service:
        name: firewalld
        state: restarted

    - name: "allow access tcp port {{item}}"
      firewalld:
        port: "{{item}}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 88/tcp
        - 89/tcp
