---
- name: loop and when
  hosts: web
  vars:
    numbers:
     - a
     - b
  tasks:
    - name: print message
      debug:
        msg: "print {{item}}"

      when: number1 is defined 
      loop: "{{numbers}}"

